const display = document.getElementById('stopw');
const ao5text = document.getElementById("ao5");
const ao12text = document.getElementById("ao12");
const ao50text = document.getElementById("ao50");
const meantext = document.getElementById("mean");
const besttext = document.getElementById("best");
const dellast = document.getElementById("dellast");
const penalty = document.getElementById("penalty");
const scramble = document.getElementById("scramble");
const count = document.getElementById("count");
const cubetype = document.getElementById("cube");
const copyao5 = document.getElementById("copyao5");

let lastsolve = 0;
let lastscramble = "";
let startTime = 0;
let timerInterval = null;
let timerState = "idle";
let holdTimeout = null;
let solves = [];
let fullsolves = [];

function formatCubeTime(ms) {
    let totalSeconds = ms / 1000;
    return totalSeconds.toFixed(2);
}

function updateDisplay() {
    const elapsed = Date.now() - startTime;
    display.textContent = formatCubeTime(elapsed);
}

function calculateAverage(arr) {
    if (!arr || arr.length < 3) return 0;
    const sorted = [...arr].sort((a, b) => a - b);
    sorted.pop();   
    sorted.shift(); 
    return sorted.reduce((sum, num) => sum + num, 0) / sorted.length;
}

function calculateMean(arr) {
    if (!arr || arr.length === 0) return 0;
    return arr.reduce((sum, num) => sum + num, 0) / arr.length;
}

function deleteLastSolve() {
    if (solves.length === 0) {
        alert("No solves to delete!");
        return;
    }

    const userConfirmed = confirm("Are you sure you want to delete your last solve?");
    
    if (!userConfirmed) {
        return; 
    }

    solves.pop(); 
    fullsolves.pop(); 
    if (solves.length > 0) {
        meantext.textContent = "Mean: " + calculateMean(solves).toFixed(2);
        const smallest = Math.min(...solves);
        besttext.textContent = "Best: " + smallest;
    } else {
        meantext.textContent = "Mean: 0.00";
        besttext.textContent = "Best: 0.00";
    }

    if (solves.length >= 5) {
        const lastfive = solves.slice(-5);
        ao5text.textContent = "Ao5: " + calculateAverage(lastfive).toFixed(2);
    } else {
        ao5text.textContent = "Ao5: - ";
    }

    if (solves.length >= 12) {
        const lasttwelve = solves.slice(-12);
        ao12text.textContent = "Ao12: " + calculateAverage(lasttwelve).toFixed(2);
    } else {
        ao12text.textContent = "Ao12: - ";
    }

    if (solves.length >= 50) {
        const lastfifty = solves.slice(-50);
        ao50text.textContent = "Ao50: " + calculateAverage(lastfifty).toFixed(2);
    } else {
        ao50text.textContent = "Ao50: - ";
    }
    count.textContent = "Count: "+solves.length;
    display.textContent = "0.00";
}

async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    alert('Text successfully copied to clipboard!');
  } catch (err) {
    alert('Failed to copy text: ', err);
  }
}

function copyLastFive() {
    if (solves.length < 5) {
        alert("You need at least 5 solves to copy!");
        return;
    }

    const lastFiveSolves = fullsolves.slice(-5);
    const lastFiveTimes = solves.slice(-5);
    const calculatedAo5 = calculateAverage(lastFiveTimes).toFixed(2);
    const sortedTimes = [...lastFiveTimes].sort((a, b) => a - b);
    const bestTime = sortedTimes[0];
    const worstTime = sortedTimes[sortedTimes.length - 1];

    let hasBracketedBest = false;
    let hasBracketedWorst = false;
    const formattedSolvesString = lastFiveSolves.map((solve, index) => {
        let timeString = solve.time.toFixed(2);
        if (solve.time === bestTime && !hasBracketedBest) {
            timeString = `(${timeString})`;
            hasBracketedBest = true;
        } else if (solve.time === worstTime && !hasBracketedWorst) {
            timeString = `(${timeString})`;
            hasBracketedWorst = true;
        }
        
        return `${index + 1}. ${timeString}   ${solve.scramble}`;
    }).join("\n");

    const finalClipboardText = `Generated by SammyTimer\nAo5: ${calculatedAo5}\n\nSolves:\n${formattedSolvesString}`;

    copyToClipboard(finalClipboardText);
}

function addTwoPenalty() {
    if (solves.length === 0) {
        alert("No solves to mark!");
        return;
    }
    solves[solves.length - 1] = Number(solves[solves.length - 1]) + 2;
    if (fullsolves[fullsolves.length - 1]) {
        fullsolves[fullsolves.length - 1].time += 2;
    }
    if (solves.length > 0) {
        meantext.textContent = "Mean: " + calculateMean(solves).toFixed(2);
        const smallest = Math.min(...solves);
        besttext.textContent = "Best: " + smallest;
    } else {
        meantext.textContent = "Mean: 0.00";
        besttext.textContent = "Best: 0.00";
    }

    if (solves.length >= 5) {
        const lastfive = solves.slice(-5);
        ao5text.textContent = "Ao5: " + calculateAverage(lastfive).toFixed(2);
    } else {
        ao5text.textContent = "Ao5: - ";
    }

    if (solves.length >= 12) {
        const lasttwelve = solves.slice(-12);
        ao12text.textContent = "Ao12: " + calculateAverage(lasttwelve).toFixed(2);
    } else {
        ao12text.textContent = "Ao12: - ";
    }

    if (solves.length >= 50) {
        const lastfifty = solves.slice(-50);
        ao50text.textContent = "Ao50: " + calculateAverage(lastfifty).toFixed(2);
    } else {
        ao50text.textContent = "Ao50: - ";
    }
    display.textContent = "0.00";
}

function areOpposite(face1, face2) {
    const opposites = { 'U': 'D', 'D': 'U', 'R': 'L', 'L': 'R', 'F': 'B', 'B': 'F' };
    return opposites[face1] === face2;
}

function generate3x3Scramble(length = 20) {
    const faces = ['U', 'D', 'R', 'L', 'F', 'B'];
    const modifiers = ['', "'", '2'];
    const scramble = [];
    
    let lastFace = '';
    let secondLastFace = '';

    for (let i = 0; i < length; i++) {
        let chosenFace;

        do {
            chosenFace = faces[Math.floor(Math.random() * faces.length)];
        } while (
            chosenFace === lastFace || 
            (chosenFace === secondLastFace && areOpposite(chosenFace, lastFace))
        );

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(chosenFace + chosenModifier);

        secondLastFace = lastFace;
        lastFace = chosenFace;
    }

    return scramble.join(' ');
}

function generate2x2Scramble(length = 11) {
    const faces = ['U', 'R', 'F'];
    const modifiers = ['', "'", '2'];
    const scramble = [];
    
    let lastFace = '';
    let secondLastFace = '';

    for (let i = 0; i < length; i++) {
        let chosenFace;

        do {
            chosenFace = faces[Math.floor(Math.random() * faces.length)];
        } while (
            chosenFace === lastFace || 
            (chosenFace === secondLastFace && areOpposite(chosenFace, lastFace))
        );

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(chosenFace + chosenModifier);

        secondLastFace = lastFace;
        lastFace = chosenFace;
    }

    return scramble.join(' ');
}

function generateSkewbScramble(length = 9) {
    const faces = ['L', 'R', 'D', 'U', 'B', 'r'];
    const modifiers = ['', "'"];
    const scramble = [];
    
    let lastFace = '';
    let secondLastFace = '';

    for (let i = 0; i < length; i++) {
        let chosenFace;

        do {
            chosenFace = faces[Math.floor(Math.random() * faces.length)];
        } while (
            chosenFace === lastFace || 
            (chosenFace === secondLastFace && areOpposite(chosenFace, lastFace))
        );

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(chosenFace + chosenModifier);

        secondLastFace = lastFace;
        lastFace = chosenFace;
    }

    return scramble.join(' ');
}

function generate4x4Scramble(length = 45) {
    const faces = ['U', 'D', 'R', 'L', 'F', 'B', 'Uw', 'Rw', 'Fw'];
    const modifiers = ['', "'", '2'];
    const scramble = [];
    
    let lastFace = '';
    let secondLastFace = '';

    for (let i = 0; i < length; i++) {
        let chosenFace;

        do {
            chosenFace = faces[Math.floor(Math.random() * faces.length)];
        } while (
            chosenFace === lastFace || 
            (chosenFace === secondLastFace && areOpposite(chosenFace, lastFace))
        );

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(chosenFace + chosenModifier);

        secondLastFace = lastFace;
        lastFace = chosenFace;
    }

    return scramble.join(' ');
}

function generate5x5Scramble(length = 60) {
    const faces = ['U', 'D', 'R', 'L', 'F', 'B', 'Uw', 'Rw', 'Fw'];
    const modifiers = ['', "'", '2'];
    const scramble = [];
    
    let lastFace = '';
    let secondLastFace = '';

    for (let i = 0; i < length; i++) {
        let chosenFace;

        do {
            chosenFace = faces[Math.floor(Math.random() * faces.length)];
        } while (
            chosenFace === lastFace || 
            (chosenFace === secondLastFace && areOpposite(chosenFace, lastFace))
        );

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(chosenFace + chosenModifier);

        secondLastFace = lastFace;
        lastFace = chosenFace;
    }

    return scramble.join(' ');
}

function generateSq1Scramble(length = 14) {
    const validMoves = [0, 1, 2, 3, 4, 5, 6, -1, -2, -3, -4, -5];
    const scramble = [];

    for (let i = 0; i < length; i++) {
        let top, bottom;
        
        do {
            top = validChoice(validMoves);
            bottom = validChoice(validMoves);
        } while (top === 0 && bottom === 0);

        const topStr = top === 0 ? "0" : top;
        const bottomStr = bottom === 0 ? "0" : bottom;

        scramble.push(`(${topStr}, ${bottomStr}) /`);
    }

    return scramble.join(' ');
}

function validChoice(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function generateMegaScramble(length = 6) {
    const modifiersRD = ['++', "--"];
    const modifiersU = ['', "'"];
    const scramble = [];
    
    let r = 'R';
    let d = 'D';
    let u = 'U'

    for (let i = 0; i < length; i++) {
        const chosenModifierU = modifiersU[Math.floor(Math.random() * modifiersU.length)];
        const scramline = [];
        for (let j=1; j <= 5; j++) {
            let chosenModifierRD = '';
            chosenModifierRD = modifiersRD[Math.floor(Math.random() * modifiersRD.length)];
            scramline.push(r+chosenModifierRD);
            chosenModifierRD = modifiersRD[Math.floor(Math.random() * modifiersRD.length)];
            scramline.push(d+chosenModifierRD);
            console.log(scramline)
        }
        scramline.push(u+chosenModifierU);
        scramble.push(scramline.join(' ')+' ');
    }

    return scramble.join(' ');
}

function generatePyraScramble(length = 9, tipl=3) {
    const faces = ['L', 'R', 'B', 'U'];
    const modifiers = ['', "'"];
    const scramble = [];
    
    let lastFace = '';
    let secondLastFace = '';

    for (let i = 0; i < length; i++) {
        let chosenFace;

        do {
            chosenFace = faces[Math.floor(Math.random() * faces.length)];
        } while (
            chosenFace === lastFace || 
            (chosenFace === secondLastFace && areOpposite(chosenFace, lastFace))
        );

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(chosenFace + chosenModifier);

        secondLastFace = lastFace;
        lastFace = chosenFace;
    }
    const tipfaces = ['l', 'r', 'b', 'u'];
    const tipscramble = [];

    for (let i = 0; i <= tipl; i++) {
        
        let tipFace=tipfaces[i];

        const chosenModifier = modifiers[Math.floor(Math.random() * modifiers.length)];
        scramble.push(tipFace + chosenModifier);
    }
    return scramble.join(' ');
}

function chooseCube() {
    const selectedCube = cubetype.value;
    if (selectedCube === "3x3") {
        scramble.textContent = generate3x3Scramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "2x2") {
        scramble.textContent = generate2x2Scramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "4x4") {
        scramble.textContent = generate4x4Scramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "skewb") {
        scramble.textContent = generateSkewbScramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "pyra") {
        scramble.textContent = generatePyraScramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "5x5") {
        scramble.textContent = generate5x5Scramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "sq1") {
        scramble.textContent = generateSq1Scramble();
        console.log(scramble.textContent); 
    } else if (selectedCube === "mega") {
        scramble.textContent = generateMegaScramble();
        console.log(scramble.textContent); 
    }
}

scramble.textContent = generate3x3Scramble();

console.log(scramble.textContent); 

cubetype.addEventListener('change', (event) => {
  chooseCube();
});

copyao5.addEventListener("click", (event)=>{
    event.target.blur(); 
    copyLastFive();
});

dellast.addEventListener("click", (event)=>{
    event.target.blur(); 
    deleteLastSolve();
});

penalty.addEventListener("click", (event)=>{
    event.target.blur(); 
    addTwoPenalty();
});

scramble.addEventListener("click", (event)=>{
    event.target.blur(); 
    chooseCube();
});

window.addEventListener('keydown', (event) => {
    if (event.code === "Space") {
        event.preventDefault(); 
    }
    if (timerState === "running") {
        clearInterval(timerInterval);
        timerState = "idle";
        display.className = "idle";
        display.style.color = "red";
        updateDisplay(); 
        lastsolve = +display.textContent;
        lastscramble = scramble.textContent;
        const solveIndex = solves.length+1;
        solves.push(lastsolve);
        fullsolves[solveIndex] = {
            time: lastsolve,
            scramble: lastscramble
        };
        console.log(solves);
        console.log(fullsolves);
        chooseCube();
        if (solves.length>=5) {
            const lastfive = solves.slice(-5);
            ao5text.textContent = "Ao5: "+calculateAverage(lastfive).toFixed(2);
        }
        if (solves.length>=12) {
            const lasttwelve = solves.slice(-12);
            ao12text.textContent = "Ao12: "+calculateAverage(lasttwelve).toFixed(2);
        }        
        if (solves.length>=50) {
            const lastfifty = solves.slice(-50);
            ao5text.textContent = "Ao50: "+calculateAverage(lastfifty).toFixed(2);
        }
        meantext.textContent = "Mean: "+calculateMean(solves).toFixed(2);
        const smallest = Math.min(...solves); 
        besttext.textContent = "Best: "+smallest;
        count.textContent = "Count: "+solves.length;
        return;
    }

    if (event.code === "Space" && timerState === "idle") {
        event.preventDefault(); 
        timerState = "readying";
        display.className = "readying";
        display.style.color = "white";

        holdTimeout = setTimeout(() => {
            timerState = "ready";
            display.className = "ready";
            display.style.color = "green";
            display.textContent = "0.00";
        }, 300);
    }
});


window.addEventListener('keyup', (event) => {
    if (event.code === "Space") {
        if (timerState === "ready") {
            timerState = "running";
            display.className = "running";
            display.style.color = "white";
            display.textContent = "0.00";
            startTime = Date.now();
            timerInterval = setInterval(updateDisplay, 10);
        } else if (timerState === "readying") {

            clearTimeout(holdTimeout);
            timerState = "idle";
            display.className = "idle";
        }
    }
});
